spring:
  application:
    name: in-out-service
  datasource:
    url: jdbc:mysql://localhost:3306/appdatabase
    username: root
    password: 1234
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true



server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: eureka-0

